### ISSUE TITLE
Definitional equality of lambda is wrong?

### ISSUE THREAD

**Issue by molikto** [mortberg/cubicaltt#53]
Program

```
pred : nat -> nat = split
  zero -> zero
  suc n -> n


pred_alt : nat -> nat = split
  zero -> zero
  suc n -> n

lamtest_pred_alt: Path (nat -> nat) pred pred_alt = <i> pred_alt
```

will fail with

```
Type checking failed: path endpoints don't match for pred_alt, got (pred_alt,pred_alt), but expected (pred,pred_alt)
```

but in Coq:

```
Fixpoint add_alt (a b: nat) : nat := match a with 
| O => b
| S p => S (add_alt p b)
end.

Definition add_alt_test: (plus = add_alt) := eq_refl.
```

Type checks.

**Comment by coquand** [comment]
Yes, one considers that pred and  pred_alt are not definitionally equal.
Intuitively we add a new function pred with definitions

 pred zero = zero
 pred (suc n) = n

and the same for pred_alt and we ask

 are pred and pred_alt definitionally equal?

which calls

 are pred n and pred_alt n definitionally equal?

for n:nat variable and they are not since they are different and in normal form (we cannot
unfold any definition.)

**Comment by mortberg** [comment]
As @coquand explained we are not unfolding these definitions when checking for convertibility. Coq on the other hand sometimes applies the "delta rule" for unfolding definitions, however one has to be careful when doing this as definitions may be recursive. For details how Coq does things see:

http://adam.chlipala.net/cpdt/html/Equality.html
