### ISSUE TITLE
Solution at "hard" exercise at lecture2.ctt

### ISSUE THREAD

**Issue by xekoukou** [mortberg/cubicaltt#73]
Hello ,I can't find a way to show the undefined : 

```
-- Another example of a simple composition: compose p with its inverse
compinv (A : U) (a b : A) (p : Path A a b) : Path A a a =
 <i> comp (<_> A) (p @ i) [ (i = 0) -> <j> a, (i = 1) -> <j> p @ -j ]

exlemma (A : U) (a : A) :
  Path (Path A a a) (<j> a) (compinv A a a (<i> a)) = undefined 

-- Exercise (hard): is "compinv A a b p" Path equal to <j> a?
ex (A : U) (a b : A) (p : Path A a b) :
  Path (Path A a a) (<j> a) (compinv A a b p)
    = trans (Path A a a) (<_> a) (compinv A a a (<_> a)) (compinv A a b p) (exlemma A a)(<k> <i> comp (<_> A) (p @ (i /\ k)) [ (i = 0) -> <j> a, (i = 1) -> <j> p @ (k /\ -j) ])

```

It is from your second lecture [here](https://github.com/mortberg/cubicaltt/blob/master/lectures/lecture2.ctt#L282)

In algebraic topology, two constant paths are equal by definition.

**Comment by xekoukou** [comment]
Closing as lecture3.ctt has the answer. 

Your slides on [cubicaltt](http://www-sop.inria.fr/members/Anders.Mortberg/slides/Cornell-cubicaltt.pdf) is a good introduction to cubicaltt. You could add them with the lectures here.

**Comment by mortberg** [comment]
Indeed, the composition of two constant paths is not convertible to only one constant path in cubicaltt. I think I discuss why this is the case in some later lecture. We had a version where we tried this (by enforcing something we called "regularity"), but it never worked out. The problem is to define a "regular" composition operation for the universe.

Proving your `exlemma` should be a little easier than the original exercise, the only difference is that p is refl so that the inversion disappears. If you have done the constant square exercise of `lecture3.ctt` this should be really easy, just compute a composition in a cube with the back face being the compinv composition and all of the other sides constant. Let me know if you want a solution to it or if you can figure it out yourself.

**Comment by JoelSjogren** [comment]
Hello! This was my attempted solution:

```
ex (A : U) (a b : A) (p : Path A a b) :
  Path (Path A a a) (compinv A a b p) (<i> a) =
    <i j> comp (<_> A) (p @ i \/ j) {- bottom -} [
      (i = 0) -> <k> p @ j /\ -k, -- back
      (i = 1) -> <k> p @      -k, -- front
      (j = 0) -> <k> p @ i /\ -k, -- left
      (j = 1) -> <k> p @      -k, -- right
    ]
```
```
Type checking failed: path endpoints don't match for <j> comp (<_> A) (p @ (i \/ j)) [ (i = 0) -> <k> p @ (j /\ -k), (i = 1) -> <k> p @ -k, (j = 0) -> <k> p @ (i /\ -k), (j = 1) -> <k> p @ -k ], got (<!0> a,<!0> a), but expected (<!0> comp (<!1> A) (p @ !0) [ (!0 = 0) -> <!1> a, (!0 = 1) -> <!1> p @ -!1 ],<!0> a)
```
I then looked at the solution provided in `lecture3.ctt` and saw that it only specified 3 sides enclosed within [ ]. If I comment out the `back` line then my attempt works. Could you explain why only 3 sides are necessary? What does the pattern look like in higher dimensions?
