### ISSUE TITLE
A pattern matching for predicate function

### ISSUE THREAD

**Issue by xgrommx** [mortberg/cubicaltt#83]
Hello @mortberg I have some problem with pattern matching. This is my pretty easy code
```hs
filter(A: U) (p: A -> bool): list A -> list A = split
  nil -> nil
  cons x xs -> split@(p x -> bool) with
    true -> cons x (filter A xs)
    false -> filter A xs
```

Could you please correct it? Or provide more better solution.

Also I think this will be will be helpful, but I got error

```hs
if_then_else (A: U): bool -> A -> A -> A = split
  true -> \(x: A) (y: A) -> x
  false -> \(x: A) (y: A) -> y
```

```
Checking: if_then_else
Type checking failed: case branches does not match the data type
```

Thanks

**Comment by simhu** [comment]
Your if_then_else works for me; how did you define bool?

Regarding your filter:

The parser is for example happy with:

```
filter (A : U) (p : A -> bool): list A -> list A = split
  nil -> nil
  cons x xs -> (split@(bool -> list A) with 
      true -> cons x (filter A p xs)
      false -> filter A p xs
    ) (p x)
```
(Note that the annotation for the split is the *type* of the function
you are defining.)

But the type-checker doesn't accept this currently, as it doesn't
infer the types, even though it could since splits are annotated with
their type internally.  I'll think about whether we should add
this--but I am not really sure if anyone ever wants to write
"(split@... ...) foo".

Alternatively you could write:

```
filter (A : U) (p : A -> bool): list A -> list A = split
  nil -> nil
  cons x xs -> let ifte : bool -> list A = split
                     true -> cons x (filter A p xs)
                     false -> filter A p xs
               in ifte (p x)
```

**Comment by 5HT** [comment]
In `cubical` you need to specify constructors in split cases in the same order as they are defined in data type. In base library of `cubical` bool is defined as data bool = false | true, so obviously your code does not follow the order.

**Comment by mortberg** [comment]
Yes, as @5HT says the order of the constructors matters. This could quite easily be relaxed for normal datatypes (we actually had this at some point), but for HITs things are more subtle as the lower dimensional constructors should come before the higher dimensional ones. Maybe the best would be to have a better error message for this, feel free to make a PR with this. 

Regarding @simhu's comment I don't think `(split@... ...) foo` is useful unless we have type inference so that the type can be omitted. If we had type inference we could have a match/case construct that was sugar for `(split@... ...) foo`, but for now I think the version with a local definition using let-in/where is ok.

**Comment by mortberg** [comment]
I'm closing this issue now, but if someone wants to contribute please make a PR with a better error message for this.

**Comment by 5HT** [comment]
Thanks, @mortberg,`cubical` is the best language and implementation we have seen so far in this world :-) Please keep it simple and concise as long as possible! <3
